### ISSUE TITLE
Må ha fast ip!

### ISSUE THREAD

**Issue by Andreas-Pedersen** [Andreas-Pedersen/hansi#1]
Endre til fast ip!

**Comment by xibriz** [comment]
Det ser ut som det er veldig mye bugs rundt å sette fast IP på ESP8266. Det enkleste er nok å gå rett på ruteren å sette en "static lease" basert på MAC-adressen til ESPen.

**Comment by Andreas-Pedersen** [comment]
Ja det er slik jeg gjør det pr idag..
Men det var jo for å få den til å koble opp kjappere.

**Comment by xibriz** [comment]
Static lease å fast IP på device gir samme resultat :)
